lastupdatecheck: 0
recentrepos:
- /home/ru/git/nvim/NvChad/NvChad
- /home/ru/git/nvim/benbrastmckie/.config
- /home/ru/git/nvim/idelossa/gh.nvim
- /home/ru/git/nvim/adalessa
- /home/ru/git/nvim/Traap/nvim
- /home/ru/reinst
- /home/ru/git/nvim/AstroNvim
startuppopupversion: 5
customcommandshistory: []
hidecommandlog: false
